# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: 企鹅读书

on:
  workflow_dispatch:
  schedule:
    - cron: '*/11 * * * *'
  watch:
    type: [started]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event == 'push'

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
         
      - name: 'Install requirements'
        run: pip install -r ./requirements.txt 
        
      - name: '运行【企鹅读书】' 
        run: python3 qq_read.py 
        env:
            CONFIG: ${{ secrets.CONFIG }}

